/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-05-27 16:00:31 UTC)
 * on 2016-06-29 at 07:26:45 UTC 
 * Modify at your own risk.
 */

package com.appspot.bank_1350.transactionhistoryapi.model;

/**
 * Model definition for TransactionHistory.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the transactionhistoryapi. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class TransactionHistory extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String balance;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String deposit;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime transactionDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String transactionDescription;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long transactionId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long userId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String withdrawal;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getBalance() {
    return balance;
  }

  /**
   * @param balance balance or {@code null} for none
   */
  public TransactionHistory setBalance(java.lang.String balance) {
    this.balance = balance;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDeposit() {
    return deposit;
  }

  /**
   * @param deposit deposit or {@code null} for none
   */
  public TransactionHistory setDeposit(java.lang.String deposit) {
    this.deposit = deposit;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getTransactionDate() {
    return transactionDate;
  }

  /**
   * @param transactionDate transactionDate or {@code null} for none
   */
  public TransactionHistory setTransactionDate(com.google.api.client.util.DateTime transactionDate) {
    this.transactionDate = transactionDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTransactionDescription() {
    return transactionDescription;
  }

  /**
   * @param transactionDescription transactionDescription or {@code null} for none
   */
  public TransactionHistory setTransactionDescription(java.lang.String transactionDescription) {
    this.transactionDescription = transactionDescription;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getTransactionId() {
    return transactionId;
  }

  /**
   * @param transactionId transactionId or {@code null} for none
   */
  public TransactionHistory setTransactionId(java.lang.Long transactionId) {
    this.transactionId = transactionId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getUserId() {
    return userId;
  }

  /**
   * @param userId userId or {@code null} for none
   */
  public TransactionHistory setUserId(java.lang.Long userId) {
    this.userId = userId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getWithdrawal() {
    return withdrawal;
  }

  /**
   * @param withdrawal withdrawal or {@code null} for none
   */
  public TransactionHistory setWithdrawal(java.lang.String withdrawal) {
    this.withdrawal = withdrawal;
    return this;
  }

  @Override
  public TransactionHistory set(String fieldName, Object value) {
    return (TransactionHistory) super.set(fieldName, value);
  }

  @Override
  public TransactionHistory clone() {
    return (TransactionHistory) super.clone();
  }

}
